#!/usr/bin/env bash

if
  [[ -s "/home/vagrant/.rvm/gems/ruby-2.3.0/environment" ]]
then
  source "/home/vagrant/.rvm/gems/ruby-2.3.0/environment"
  exec ldiff "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/vagrant/.rvm/gems/ruby-2.3.0/environment'" >&2
  exit 1
fi
