#!/usr/bin/env bash

if
  [[ -s "/home/vagrant/.rvm/gems/ruby-2.3.0@global/environment" ]]
then
  source "/home/vagrant/.rvm/gems/ruby-2.3.0@global/environment"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/vagrant/.rvm/gems/ruby-2.3.0@global/environment'" >&2
  exit 1
fi
